#!/usr/bin/env ruby 

require 'rubygems'
require 'thor'

require 'lib/bank_agent'
BankAgent.config = File.dirname(__FILE__) + '/config.yml'

class CLI < Thor
  desc "download", "Download automatic accounts"
  method_options :name => :string, :type => :string
  def download
    list = if options[:name]
      BankAgent.by_name(options[:name])
    else
      BankAgent.config['accounts']
    end

    list.map {|a| BankAgent::Account.new(a) }.each(&:update)
  end

  desc "ofx <path>, [<path>, <path>, ...]", "Import ofx files"
  def ofx(*paths)
    paths.each do |path|
      BankAgent::Ofx.new(File.read(path)).import_transactions
    end
  end

  desc "paypal <file_path>", "Import paypal balance affecting csv files"
  method_option :name, :required => true
  def paypal(path)
    opts = BankAgent.by_name(options[:name]).first
    data = File.read(path)

    BankAgent::Paypal.new(data, opts).import_transactions
  end
end

CLI.start
