#!/usr/bin/env ruby 

require 'rubygems'
require 'thor'

require 'lib/bank_agent'
BankAgent.config = File.dirname(__FILE__) + '/config.yml'

class CLI < Thor
  desc "download", "Download automatic accounts"
  method_options :name => :string, :type => :string
  def download
    list = if options[:name]
      BankAgent.by_name(options[:name])
    else
      BankAgent.config['accounts']
    end

    BankAgent::Acount.update(list)
  end

  desc "ofx <path>, [<path>, <path>, ...]", "Import ofx files"
  def ofx(*paths)
    paths.each do |path|
      BankAgent::Account.import(path, 'type' => 'Ofx')
    end
  end

  desc "paypal <file_path>", "Import paypal balance affecting csv files"
  method_option :name, :required => true
  def paypal(path)
    opts = BankAgent.by_name(options[:name]).first
    BankAgent::Account.import(path, opts)
  end
end

CLI.start
